/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author ittov
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private iFrmFactura Fac;
      private ifrmCliente cli;
         private iFrmProductoE pro;
    boolean a=true;
    public Home() {
        initComponents();    
         this.setExtendedState(Home.MAXIMIZED_BOTH);
    }
    
     //Metodo para cambiar el color de los paneles 
    public void changecolor(JPanel hover, Color rand){
    hover.setBackground(rand);
    }
    
    //Metodo para cambiar el color de los botones del menu
    public void clickmenu(JPanel h1, JPanel h2,JPanel h3, int numberbool){
    if(numberbool ==1){
    h1.setBackground(new Color(243,170,28));
    h2.setBackground(new Color(255, 255, 255));
    h3.setBackground(new Color(255, 255, 255));
    }
    else{
     h1.setBackground(new Color(255, 255, 255));
    h2.setBackground(new Color(255,197,45));
   h3.setBackground(new Color(255,197,45));
    }
    }
     //Metodo para cambiar imagenes
    public void changeImage(JLabel button, String resourcheing){
    ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheing));
    button.setIcon(aimg);
    }
    
    //Metodo para cambiar tamaño del menu
    public void hideShow(JPanel menuShowhide, boolean dashboard, JLabel button){
    if(dashboard==true){
    menuShowhide.setPreferredSize(new Dimension(120, menuShowhide.getHeight()));
        changeImage(button, "/iconos/mayor.png");
    }else{
     menuShowhide.setPreferredSize(new Dimension(300, menuShowhide.getHeight()));
     changeImage(button, "/iconos/menor.png");
    }
    }
   public static boolean estaCerrado(Object obj, JDesktopPane escritorio){
       JInternalFrame[] actives = escritorio.getAllFrames();
       boolean cerrado= true;
       int i=0;
       while(i<actives.length && cerrado){
       if(actives[i]==obj){
       cerrado = false;
       }
       i++;
       }
   return cerrado;
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Encabezado = new javax.swing.JPanel();
        Opciones = new javax.swing.JPanel();
        pnMin = new javax.swing.JPanel();
        btnMin = new javax.swing.JLabel();
        pnCerrar = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        pnMax = new javax.swing.JPanel();
        btnMax = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuIconos = new javax.swing.JPanel();
        pnLogo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        espacio = new javax.swing.JPanel();
        PnOcultarMenu = new javax.swing.JPanel();
        btnOcultar = new javax.swing.JLabel();
        pnSeleccion1 = new javax.swing.JPanel();
        pnSeleccion2 = new javax.swing.JPanel();
        pnSeleccion3 = new javax.swing.JPanel();
        BtnProducto = new javax.swing.JButton();
        BtnCliente = new javax.swing.JButton();
        BtnVenta = new javax.swing.JButton();
        Padre = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        Encabezado.setBackground(new java.awt.Color(3, 4, 122));
        Encabezado.setPreferredSize(new java.awt.Dimension(800, 40));
        Encabezado.setLayout(new java.awt.BorderLayout());

        Opciones.setBackground(new java.awt.Color(3, 4, 122));
        Opciones.setMinimumSize(new java.awt.Dimension(150, 100));
        Opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMin.setBackground(new java.awt.Color(3, 4, 122));
        pnMin.setPreferredSize(new java.awt.Dimension(50, 50));
        pnMin.setLayout(new java.awt.BorderLayout());

        btnMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/minimize.png"))); // NOI18N
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinMouseExited(evt);
            }
        });
        pnMin.add(btnMin, java.awt.BorderLayout.CENTER);

        Opciones.add(pnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        pnCerrar.setBackground(new java.awt.Color(3, 4, 122));
        pnCerrar.setPreferredSize(new java.awt.Dimension(50, 50));
        pnCerrar.setLayout(new java.awt.BorderLayout());

        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/close.png"))); // NOI18N
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        pnCerrar.add(btnClose, java.awt.BorderLayout.CENTER);

        Opciones.add(pnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 50, 40));

        pnMax.setBackground(new java.awt.Color(3, 4, 122));
        pnMax.setPreferredSize(new java.awt.Dimension(50, 50));
        pnMax.setLayout(new java.awt.BorderLayout());

        btnMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/maximize-size-option.png"))); // NOI18N
        btnMax.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMax.setVerifyInputWhenFocusTarget(false);
        btnMax.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaxMouseExited(evt);
            }
        });
        pnMax.add(btnMax, java.awt.BorderLayout.CENTER);

        Opciones.add(pnMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 40));

        Encabezado.add(Opciones, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(3, 4, 122));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CEMAGRI");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        Encabezado.add(jPanel4, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Encabezado, java.awt.BorderLayout.PAGE_START);

        Menu.setPreferredSize(new java.awt.Dimension(300, 450));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuIconos.setBackground(new java.awt.Color(255, 197, 45));
        MenuIconos.setPreferredSize(new java.awt.Dimension(300, 480));
        MenuIconos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLogo.setBackground(new java.awt.Color(255, 197, 45));
        pnLogo.setPreferredSize(new java.awt.Dimension(50, 50));
        pnLogo.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo-blanco.png"))); // NOI18N
        pnLogo.add(jLabel6, java.awt.BorderLayout.CENTER);

        MenuIconos.add(pnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 130, 90));

        espacio.setBackground(new java.awt.Color(255, 197, 45));

        javax.swing.GroupLayout espacioLayout = new javax.swing.GroupLayout(espacio);
        espacio.setLayout(espacioLayout);
        espacioLayout.setHorizontalGroup(
            espacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        espacioLayout.setVerticalGroup(
            espacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        MenuIconos.add(espacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        PnOcultarMenu.setBackground(new java.awt.Color(255, 197, 45));
        PnOcultarMenu.setPreferredSize(new java.awt.Dimension(10, 32));
        PnOcultarMenu.setLayout(new java.awt.BorderLayout());

        btnOcultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menor.png"))); // NOI18N
        btnOcultar.setIconTextGap(10);
        btnOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOcultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOcultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOcultarMouseExited(evt);
            }
        });
        PnOcultarMenu.add(btnOcultar, java.awt.BorderLayout.CENTER);

        MenuIconos.add(PnOcultarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 70));

        pnSeleccion1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnSeleccion1Layout = new javax.swing.GroupLayout(pnSeleccion1);
        pnSeleccion1.setLayout(pnSeleccion1Layout);
        pnSeleccion1Layout.setHorizontalGroup(
            pnSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        pnSeleccion1Layout.setVerticalGroup(
            pnSeleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        MenuIconos.add(pnSeleccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 10));

        pnSeleccion2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnSeleccion2Layout = new javax.swing.GroupLayout(pnSeleccion2);
        pnSeleccion2.setLayout(pnSeleccion2Layout);
        pnSeleccion2Layout.setHorizontalGroup(
            pnSeleccion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        pnSeleccion2Layout.setVerticalGroup(
            pnSeleccion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        MenuIconos.add(pnSeleccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, -1));

        pnSeleccion3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnSeleccion3Layout = new javax.swing.GroupLayout(pnSeleccion3);
        pnSeleccion3.setLayout(pnSeleccion3Layout);
        pnSeleccion3Layout.setHorizontalGroup(
            pnSeleccion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        pnSeleccion3Layout.setVerticalGroup(
            pnSeleccion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        MenuIconos.add(pnSeleccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 330, -1));

        BtnProducto.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        BtnProducto.setForeground(new java.awt.Color(255, 255, 255));
        BtnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/caja.png"))); // NOI18N
        BtnProducto.setText("Productos");
        BtnProducto.setContentAreaFilled(false);
        BtnProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnProducto.setIconTextGap(40);
        BtnProducto.setInheritsPopupMenu(true);
        BtnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnProductoMouseExited(evt);
            }
        });
        BtnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductoActionPerformed(evt);
            }
        });
        MenuIconos.add(BtnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 110));

        BtnCliente.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        BtnCliente.setForeground(new java.awt.Color(255, 255, 255));
        BtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente.png"))); // NOI18N
        BtnCliente.setText("Cliente");
        BtnCliente.setContentAreaFilled(false);
        BtnCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnCliente.setIconTextGap(45);
        BtnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnClienteMouseExited(evt);
            }
        });
        BtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteActionPerformed(evt);
            }
        });
        MenuIconos.add(BtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 110));

        BtnVenta.setBackground(new java.awt.Color(102, 102, 0));
        BtnVenta.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        BtnVenta.setForeground(new java.awt.Color(255, 255, 255));
        BtnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/compras.png"))); // NOI18N
        BtnVenta.setText("Venta");
        BtnVenta.setContentAreaFilled(false);
        BtnVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnVenta.setIconTextGap(45);
        BtnVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnVentaMouseExited(evt);
            }
        });
        BtnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentaActionPerformed(evt);
            }
        });
        MenuIconos.add(BtnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 100));

        Menu.add(MenuIconos, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        Padre.setBackground(new java.awt.Color(180, 180, 180));
        Padre.setLayout(new java.awt.BorderLayout());

        escritorio.setOpaque(false);
        escritorio.setLayout(new java.awt.BorderLayout());
        Padre.add(escritorio, java.awt.BorderLayout.CENTER);

        getContentPane().add(Padre, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1593, 847));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked
 
    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
     changecolor(pnCerrar, new Color(2, 2, 61));
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        changecolor(pnCerrar, new Color(3,4,122)); // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseClicked
      if(this.getExtendedState()!= Home.MAXIMIZED_BOTH){
      this.setExtendedState(Home.MAXIMIZED_BOTH);
      }
      else{
      this.setExtendedState(Home.NORMAL);
      }
    }//GEN-LAST:event_btnMaxMouseClicked

    private void btnMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseEntered
        changecolor(pnMax, new Color(2, 2, 61));
    }//GEN-LAST:event_btnMaxMouseEntered

    private void btnMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxMouseExited
       changecolor(pnMax, new Color(3,4,122));
    }//GEN-LAST:event_btnMaxMouseExited

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        
    }//GEN-LAST:event_btnMinMouseClicked

    private void btnMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseEntered
      changecolor(pnMin, new Color(2, 2, 61));
    }//GEN-LAST:event_btnMinMouseEntered

    private void btnMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseExited
        changecolor(pnMin, new Color(3,4,122));
    }//GEN-LAST:event_btnMinMouseExited

    private void btnOcultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseExited
        changecolor(PnOcultarMenu, new Color( 255, 197, 45));
    }//GEN-LAST:event_btnOcultarMouseExited

    private void btnOcultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseEntered
        changecolor(PnOcultarMenu, new Color( 243,170,28));
    }//GEN-LAST:event_btnOcultarMouseEntered

    private void btnOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseClicked
        if(a==true){
            hideShow(Menu, a, btnOcultar);
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        }
        else{
            hideShow(Menu, a , btnOcultar);
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_btnOcultarMouseClicked

    private void BtnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductoActionPerformed
       if(estaCerrado(pro, escritorio)) {  
            pro = new iFrmProductoE();
            escritorio.add(pro);
            escritorio.moveToFront(pro);
            pro.setSize(escritorio.getWidth(), escritorio.getHeight());
            pro.setLocation(0, 0);
            pro.setVisible(true);
        } else{
            escritorio.moveToFront(pro);
        }
    }//GEN-LAST:event_BtnProductoActionPerformed

    private void BtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteActionPerformed
        if(estaCerrado(cli, escritorio)) {  
            cli = new ifrmCliente();
            escritorio.add(cli);
            escritorio.moveToFront(cli);
            cli.setSize(escritorio.getWidth(), escritorio.getHeight());
            cli.setLocation(0, 0);
            cli.setVisible(true);
        } else{
            escritorio.moveToFront(cli);
        }
    }//GEN-LAST:event_BtnClienteActionPerformed

    private void BtnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentaActionPerformed

        if(estaCerrado(Fac, escritorio)) {  
            Fac = new iFrmFactura();
            escritorio.add(Fac);
            escritorio.moveToFront(Fac);
            Fac.setSize(escritorio.getWidth(), escritorio.getHeight());
            Fac.setLocation(0, 0);
            Fac.setVisible(true);
        } else{
            escritorio.moveToFront(Fac);
        }
    }//GEN-LAST:event_BtnVentaActionPerformed

    private void BtnVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVentaMouseEntered
        clickmenu(pnSeleccion3, pnSeleccion1,pnSeleccion2, 1);
    }//GEN-LAST:event_BtnVentaMouseEntered

    private void BtnVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVentaMouseExited
        changecolor(pnSeleccion3, Color.WHITE);
    }//GEN-LAST:event_BtnVentaMouseExited

    private void BtnProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProductoMouseEntered
        clickmenu(pnSeleccion2, pnSeleccion1,pnSeleccion3, 1);
    }//GEN-LAST:event_BtnProductoMouseEntered

    private void BtnProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProductoMouseExited
       changecolor(pnSeleccion2, Color.WHITE);
    }//GEN-LAST:event_BtnProductoMouseExited

    private void BtnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClienteMouseEntered
      clickmenu(pnSeleccion1, pnSeleccion2,pnSeleccion3, 1);
    }//GEN-LAST:event_BtnClienteMouseEntered

    private void BtnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClienteMouseExited
        changecolor(pnSeleccion1, Color.WHITE);
    }//GEN-LAST:event_BtnClienteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCliente;
    private javax.swing.JButton BtnProducto;
    private javax.swing.JButton BtnVenta;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuIconos;
    private javax.swing.JPanel Opciones;
    private javax.swing.JPanel Padre;
    private javax.swing.JPanel PnOcultarMenu;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMax;
    private javax.swing.JLabel btnMin;
    private javax.swing.JLabel btnOcultar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JPanel espacio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnCerrar;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnMax;
    private javax.swing.JPanel pnMin;
    private javax.swing.JPanel pnSeleccion1;
    private javax.swing.JPanel pnSeleccion2;
    private javax.swing.JPanel pnSeleccion3;
    // End of variables declaration//GEN-END:variables
}
