/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Controladores.cotrolCliente;
import Entidades.Clientes;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ittov
 */

public class ifrmCliente extends javax.swing.JInternalFrame {
       public static String id,cliente,direccion,DUI,NIT,NRC,celular, telefono, estado;

   
    
    /**
     * Creates new form ifrmCliente
     */
    public ifrmCliente() {
        initComponents();
        buscarCliente();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDUI = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNRC = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Mantenimiento Clientes");
        setVisible(true);

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 900));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, -1));

        txtNombre.setBackground(new java.awt.Color(0, 51, 102));
        txtNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txtNombre.setSelectionColor(new java.awt.Color(102, 102, 102));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 400, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(0, 51, 102));
        txtID.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txtID.setSelectionColor(new java.awt.Color(102, 102, 102));
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, 30));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIT");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        txtNIT.setBackground(new java.awt.Color(0, 51, 102));
        txtNIT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNIT.setForeground(new java.awt.Color(255, 255, 255));
        txtNIT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txtNIT.setSelectionColor(new java.awt.Color(102, 102, 102));
        jPanel3.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 200, 30));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DUI");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtDUI.setBackground(new java.awt.Color(0, 51, 102));
        txtDUI.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDUI.setForeground(new java.awt.Color(255, 255, 255));
        txtDUI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txtDUI.setSelectionColor(new java.awt.Color(102, 102, 102));
        txtDUI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDUIKeyReleased(evt);
            }
        });
        jPanel3.add(txtDUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 160, 30));

        txtDireccion.setBackground(new java.awt.Color(0, 51, 102));
        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setRows(5);
        txtDireccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        TxtDireccion.setViewportView(txtDireccion);

        jPanel3.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 390, 110));

        txtTelefono.setBackground(new java.awt.Color(0, 51, 102));
        txtTelefono.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txtTelefono.setSelectionColor(new java.awt.Color(102, 102, 102));
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, 30));

        btnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/disquete.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setIconTextGap(15);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 160, 70));

        btnLimpiar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setIconTextGap(15);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 160, 70));

        btnEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setIconTextGap(15);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 160, 70));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dirección");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        chkEstado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        chkEstado.setForeground(new java.awt.Color(255, 255, 255));
        chkEstado.setSelected(true);
        chkEstado.setText("Activo");
        chkEstado.setContentAreaFilled(false);
        jPanel3.add(chkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 70, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Teléfono");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        btnEditar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnEditar.setContentAreaFilled(false);
        btnEditar.setIconTextGap(15);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 160, 70));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NRC");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txtNRC.setBackground(new java.awt.Color(0, 51, 102));
        txtNRC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNRC.setForeground(new java.awt.Color(255, 255, 255));
        txtNRC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txtNRC.setSelectionColor(new java.awt.Color(102, 102, 102));
        jPanel3.add(txtNRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 130, 30));

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblCliente.setBackground(new java.awt.Color(102, 102, 102));
        tblCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tblCliente.setForeground(new java.awt.Color(255, 255, 255));
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setGridColor(new java.awt.Color(255, 255, 255));
        tblCliente.setSelectionBackground(new java.awt.Color(0, 0, 102));
        tblCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCliente.setShowVerticalLines(false);
        tblCliente.getTableHeader().setReorderingAllowed(false);
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(0, 51, 102));
        txtBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        txtBuscar.setSelectionColor(new java.awt.Color(102, 102, 102));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 490, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         Clientes cl = new Clientes();
    cotrolCliente ctCl = new cotrolCliente();   
        if(txtNombre.getText().equals("") ){
        JOptionPane.showMessageDialog(null, "Escriba un nombre al cliente", "Mensaje de sistema", 1);   
    }else{
            int response = JOptionPane.showConfirmDialog(this, "¿Quieres Guardar este usuario?","Confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        try {
         
           cl.setCli_Nombre(txtNombre.getText());
           cl.setCli_Direccion(txtDireccion.getText());
           cl.setCli_DUI(txtDUI.getText());
           cl.setCli_NIT(txtNIT.getText());
           cl.setCli_NRC(txtNRC.getText());
           cl.setCli_Telefono(txtTelefono.getText());
           if(chkEstado.isSelected()){
           cl.setCli_Activo(1);
           }else{
           cl.setCli_Activo(0);
           }
           
           if (response== JOptionPane.YES_OPTION){
           ctCl.InsertarPersona(cl);
           limpiar();
           buscarCliente();
           }
           
        } catch (Exception e) {
        }
            
            }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDUIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDUIKeyReleased
    
    }//GEN-LAST:event_txtDUIKeyReleased

    public void limpiar(){
    txtNombre.setText("");
    txtDireccion.setText("");
    txtDUI.setText("");
    txtNIT.setText("");
    txtID.setText("");
    txtTelefono.setText("");
     txtNRC.setText("");
    }
    
    void seleccionar(){
       int fila = tblCliente.getSelectedRow();
       if(fila >=0){
        id = String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 0));
        NRC= String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 1));
      cliente= String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 2));
       DUI =String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 3));
       NIT = String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 4));
       telefono= String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 5));
       direccion =String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 6));
       estado =String.valueOf(tblCliente.getModel().getValueAt(tblCliente.getSelectedRow(), 7));
       }
       else{
           JOptionPane.showMessageDialog(null,"Seleccione una fila");
       }
}
    
    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       buscarCliente();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
          Clientes cl = new Clientes();
    cotrolCliente ctCl = new cotrolCliente();   
        if(txtNombre.getText().equals("") ){
        JOptionPane.showMessageDialog(null, "Escriba un nombre al cliente", "Mensaje de sistema", 1);   
    }else{
            int response = JOptionPane.showConfirmDialog(this, "¿Quieres editar este usuario?","Confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        try {
          cl.setCli_Codigo(Integer.parseInt(txtID.getText()));
           cl.setCli_Nombre(txtNombre.getText());
           cl.setCli_Direccion(txtDireccion.getText());
           cl.setCli_DUI(txtDUI.getText());
           cl.setCli_NIT(txtNIT.getText());
           cl.setCli_NRC(txtNRC.getText());
           cl.setCli_Telefono(txtTelefono.getText());
           if(chkEstado.isSelected()){
           cl.setCli_Activo(1);
           }else{
           cl.setCli_Activo(0);
           }
           
           if (response== JOptionPane.YES_OPTION){
           ctCl.ActualizarCliente(cl);
           System.out.println("hola");
           limpiar();
           buscarCliente();
           }
           
        } catch (Exception e) {
        }
            
            }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
      seleccionar();
      txtID.setText(id);
      txtNombre.setText(cliente);
      txtDireccion.setText(direccion);
      txtNRC.setText(NRC);
      txtDUI.setText(DUI);
      txtNIT.setText(NIT);
      txtTelefono.setText(telefono);
       if(estado.equals("Activo")){
       chkEstado.setSelected(true);
       }else{
       chkEstado.setSelected(false);
       }
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed
    public void buscarCliente(){
    String Titulo[]={"ID","NRC","NOMBRE","DUI","NIT","TELEFONO","DIRECCION","Estado"};
   DefaultTableModel bc = new DefaultTableModel(null, Titulo){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
};
   
   Clientes cl = new Clientes();
   cl.setCli_Nombre(txtBuscar.getText());
   cotrolCliente ctCl = new cotrolCliente();
   ArrayList<Clientes> Cl= ctCl.BuscarClientes(cl);
   Iterator i =  Cl.iterator();
   
    
   String Filas[] = new String[8];
     while (i.hasNext()) {
      
        Clientes C;
        String estado;
        C= (Clientes)i.next();
        if(C.getCli_Activo()==1){ 
            estado="Activo";    
     }else{
        estado="Desactivado"; 
        }
        Filas[0]=String.valueOf(C.getCli_Codigo());
        Filas[1]= C.getCli_NRC();
        Filas[2]=C.getCli_Nombre();
        Filas[3]=C.getCli_DUI();
        Filas[4]=C.getCli_NIT();
         Filas[5]=C.getCli_Telefono();
           Filas[6]=C.getCli_Direccion();
             Filas[7]= estado;
        bc.addRow(Filas);
    }
     tblCliente.setModel(bc);
  
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TxtDireccion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    public static javax.swing.JCheckBox chkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblCliente;
    public static javax.swing.JTextField txtBuscar;
    public static javax.swing.JTextField txtDUI;
    public static javax.swing.JTextArea txtDireccion;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtNIT;
    public static javax.swing.JTextField txtNRC;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
